# Generated by Django 5.1.4 on 2025-02-02 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbonex_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_annual_mitigations",
                    models.PositiveIntegerField(
                        help_text="Estimated CO₂ mitigations per year"
                    ),
                ),
                ("project_type", models.CharField(max_length=100)),
                ("sector", models.CharField(max_length=100)),
                ("methodology", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "medias",
                    models.URLField(
                        blank=True, help_text="URL to project media files", null=True
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("number_of_credits", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
