# Generated by Django 5.1.4 on 2025-02-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carbonex_app", "0002_project"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
