# Generated by Django 5.1.4 on 2025-02-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbonex_app", "0005_trade"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Manually managed user balance for MVP",
                max_digits=20,
            ),
        ),
    ]
