# Generated by Django 5.1.4 on 2025-02-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbonex_app", "0006_customuser_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="balance",
        ),
        migrations.AddField(
            model_name="customuser",
            name="wallet_address",
            field=models.CharField(blank=True, max_length=42, null=True, unique=True),
        ),
    ]
