# Generated by Django 5.1.4 on 2025-03-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbonex_app", "0007_remove_customuser_balance_customuser_wallet_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="crediting_period",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="issued",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="product",
            field=models.CharField(default="VER", max_length=3),
        ),
        migrations.AddField(
            model_name="project",
            name="retired",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="sdg",
            field=models.JSONField(
                blank=True, help_text="Array of up to 17 integers (max)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("listed", "Listed"),
                    ("design_certified", "Gold Standard Certified design"),
                    ("project_certified", "Gold Standard Certified Project"),
                ],
                default="planned",
                max_length=20,
            ),
        ),
    ]
