# Generated by Django 5.1.4 on 2025-03-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbonex_app", "0009_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="Latitute coordinate ", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="longitude coordinate", null=True
            ),
        ),
    ]
